### ISSUE TITLE
Screen brightness stopped working on Windows when booting through OpenCore.

### ISSUE THREAD

**Issue by victorwitkamp** [baobaoit/Asus-ROG-GL552VW-OC#13]
Are you experiencing the same? 

I see \_SB.PCI0.GFX0.PNLF as "unknown device" in Windows Device Manager returning an error 45 (not connected).
I'm running Asus ATK version 1.0.0061, and it recognizes that I'm adjusting the brightness using the keyboard, but the brightness level stays the same.

Appreciate your great work!

**Comment by baobaoit** [comment]
Hi @victorwitkamp,

I see you write that you are “booting through OC”. As my knowledge, if you didn’t install Windows via Bootcamp on MacOS, so don’t booting Windows through OC, because this option is for Bootcamp. It will injected the ACPI patched into Windows so it likely using Windows on a real Mac.

You need to booting through Boot menu (ESC).

I don’t use dual boot with Windows anymore, so it is limited support for dual boot at here.

Thank you.

**Comment by victorwitkamp** [comment]
Wait that's true, I probably need to install the bootcamp drivers in order to get it working since changing brightness does work in OS X. 

Pointed me in the right direction!

**Comment by baobaoit** [comment]
Hi @victorwitkamp,

Try [this](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootcamp.html#booting-windows-error-ocb-startimage-failed-already-started)

Thank you.

**Comment by victorwitkamp** [comment]
Bootcamp drivers did it. Does not work using the Fn + F4/F5 keys though, but that's not a big deal. 👍
